name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust this if you're using a different default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3


      # Step 3: Replace the placeholder in the HTML file with the secret
      - name: Inject EMAILJS Public Key into HTML
        run: |
          sed -i "s/REPLACE_WITH_PUBLIC_KEY/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" main.html

      # Step 4: Set up Git configuration
      - name: Set up Git config
        run: |
          git config user.name "sachin koirala"
          git config user.email "sachinkoirala9999@gmail.com"
          git remote set-url origin https://github.com/${{ github.repository }}.git  # Update the remote URL

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Root folder for deployment
          destination_branch: gh-pages  # Ensure this branch is used
